apiVersion: apps/v1
kind: Deployment

metadata:
  name: adservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: adservice

  template:
    metadata:
      labels:
        app: adservice

    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5

      containers:
        - name: server

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: PORT
              value: "9555"

          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=:9555"

          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 15
            exec:
              command:
                - "/bin/grpc_health_probe"
                - "-addr=:9555"

          resources:
{{ toYaml .Values.resources | indent 12 }}
