name: PaymentService CI

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'src/paymentservice/**'

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-build.yml
    with:
      service_name: paymentservice
    secrets: inherit
